language:
  - ruby
rvm:
  - 1.9.3-p329
env:
  - RAILS=3.2.11
branches:
  only:
    - master
before_install:
  - gem update --system
  - gem --version
before_script:
  - psql -c 'create database recipe_server_test' -U postgres
  - 'rake db:migrate'